name: trajan
channels:
  - conda-forge
dependencies:
  - xarray[complete]<2025.9.0
  - pandas>=2
  - zarr
  - numpy
  - scipy
  - netcdf4
  - h5netcdf
  - bottleneck
  - coloredlogs
  - pytest
  - pytest-benchmark
  - pytest-mpl
  - pytest-cov
  - matplotlib
  - cartopy
  - pyproj
  - toml
  - click
  - roaring-landmask
  - cf_xarray>=0.8.0
  - opendrift
